version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:xjDpCuVnI/nLPgbiPfTjCDVe3+JevdSiS4MbWsfE/t0"
      - run:
          name: Connect to DigitalOcean Droplet via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
              echo "Iniciando comandos no servidor remoto"
              cd /var/www/casemeguia/Guia-de-Fornecedores-backend
              ./deploy.sh
              echo "Comandos concluídos"
            EOF

workflows:
  deploy-workflow: 
    jobs:
      - deploy