version: 2.1

jobs:
  droplet_connection:
    docker:
        - image: cimg/base:current

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:xjDpCuVnI/nLPgbiPfTjCDVe3+JevdSiS4MbWsfE/t0"
      - run:
          name: Connect to DigitalOcean droplet via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP
  build:
    steps:
      - checkout
      - run:
          name: Build
          command: |
            echo > "teste.txt" > teste.txt
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            echo > "teste2.txt" > teste2.txt

workflows:
  build_and_deploy:
    jobs:
      - droplet_connection:
          filters:
            branches:
              only:
                - develop
      - build:
          requires:
            - droplet_connection
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop