version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:xjDpCuVnI/nLPgbiPfTjCDVe3+JevdSiS4MbWsfE/t0"
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - run:
          name: Connect to DigitalOcean Droplet via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
              node -v
            EOF
workflows:
  deploy-workflow: 
    jobs:
      - deploy