version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:xjDpCuVnI/nLPgbiPfTjCDVe3+JevdSiS4MbWsfE/t0"
      - run:
          name: Connect to DigitalOcean Droplet via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "cd ..; ls"
workflows:
  deploy-workflow: 
    jobs:
      - deploy